name: build-push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  GIT_USER: luoshieryi
  GIT_EMAIL: fhaoze@gmail.com

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
        pnpm-version: [7]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - uses: pnpm/action-setup@v2.2.2
      with:
        version: ${{ matrix.pnpm-version }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Environments
      env:
        HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
      run: |
        sudo timedatectl set-timezone "Asia/Shanghai"
        mkdir -p ~/.ssh/
        echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name $GIT_USER
        git config --global user.email $GIT_EMAIL

    - name: Build
      run: pnpm install && pnpm build

    - name: Deploy - luoshieryi.github.io
      run: pnpm deploy

    - name: Clean - gothic-lolita.moe
      uses: appleboy/ssh-action@master
      env:
        SCRIPT: rm -rf ${{ secrets.NGINX_PATH }}/html
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        password: ${{ secrets.EC2_PWD }}
        script: bash -c "$SCRIPT"

    - name: Rename public
      run: mv public html

    - name: Deploy - gothic-lolita
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        password: ${{ secrets.EC2_PWD }}
        source: "./html"
        target: ${{ secrets.NGINX_PATH }}
#        rmRemote: "true"

